spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/vollmed_api
    username: developer
    password: 123456789
  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: never

API:
  security:
    token:
      secret: ${JWT_SECRET:12345678}